package day18;

import java.util.Scanner;

public class ExceptionDemo {

	public static void main(String[] args) {
		
		System.out.println("Program started.....");
		Scanner sc=new Scanner(System.in);
		/*System.out.println("Enter Number");
		int num=sc.nextInt();
		System.out.println(100/num); // Arithmatic exception
		
		*/
		
		/*int a[]=new int[5];
		System.out.println("Enter the Position(0-4): ");
		int pos=sc.nextInt();
		System.out.println("Enter a value");
		int value=sc.nextInt();
		a[pos]=value;
		System.out.println(a[pos]);
		
		*/
		
		/*String s="welcome";
		int a=Integer.parseInt(s);
		System.out.println(a);
		*/
		
		
		String s=null;
		System.out.println(s.length());
		
		
		System.out.println("Program is completed");
		System.out.println("Program exited...");
		
		
		
		
		
		
		
		
		
		

	}

}
